main: rpg.rpg_base.RPG_Base
version: 0.1
name: "RPG_Base"
api-version: '1.19'
load: STARTUP
commands:
  EnduranceLVLADD:
    description: "Adds level to Endurance stat"
    aliases: [eladd]
  EnduranceLVLREM:
    description: "Removes level to Endurance stat"
    aliases: [elrem]
  Skills:
    description: "Shows skill gui"
  LevelAdd:
    description: "Increases player level by given amount"
    aliases: [lvladd]
  RPG:
    description: "Basic utility command with addons"