main: rpg.rpg_base.RPG_Base
version: 0.1
name: "RPG_Base"
api-version: '1.19'
load: STARTUP
commands:
  EnduranceLVLADD:
    description: "Adds level to Endurance stat"
    usage: /EnduranceLVLADD <player>
    aliases: [eladd]
  EnduranceLVLREM:
    description: "Removes level to Endurance stat"
    usage: /EnduranceLVLREM <player>
    aliases: [elrem]
  Skills:
    description: "Shows skill gui"
    usage: /Skills
  LevelAdd:
    description: "Increases player level by given amount"
    usage: /LevelAdd <player>
    aliases: [lvladd]
